# Generated by Django 4.0.5 on 2022-06-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=45)),
                ('account', models.CharField(max_length=128, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('point', models.CharField(default='100000', max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
