# Generated by Django 4.0.5 on 2022-06-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fragrance',
            name='products',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='fragrance',
            field=models.ManyToManyField(db_table='products_fragrances', to='products.fragrance'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredient',
            field=models.ManyToManyField(db_table='products_ingredients', to='products.ingredient'),
        ),
    ]
